# Generated by Django 5.2.1 on 2025-05-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playbook',
            name='path',
        ),
        migrations.AddField(
            model_name='playbook',
            name='git_repo',
            field=models.URLField(default='', help_text='Git repository URL for the playbook'),
        ),
        migrations.AddField(
            model_name='playbook',
            name='modules',
            field=models.TextField(blank=True, default='', help_text='Comma-separated list of additional Ansible modules to install'),
        ),
        migrations.AddField(
            model_name='playbook',
            name='playbook_file',
            field=models.CharField(default='', help_text='Playbook YAML file to run (relative to project root)', max_length=1024),
        ),
        migrations.AddField(
            model_name='playbook',
            name='project_root',
            field=models.CharField(default='', help_text='Root path of the Ansible project after clone', max_length=1024),
        ),
        migrations.AddField(
            model_name='playbook',
            name='repo_branch',
            field=models.CharField(default='main', help_text='Branch to use from the repository', max_length=255),
        ),
    ]
