# Generated by Django 5.2.1 on 2025-05-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_playbook_path_playbook_git_repo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbookrun',
            name='artifact_path',
            field=models.CharField(blank=True, help_text='Path to the artifact directory for this run', max_length=1024, null=True),
        ),
    ]
