# Generated by Django 5.2.1 on 2025-05-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_playbookrun_artifact_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbookrun',
            name='ansible_command',
            field=models.TextField(blank=True, help_text='The ansible-runner command used for this run', null=True),
        ),
        migrations.AddField(
            model_name='playbookrun',
            name='git_command',
            field=models.TextField(blank=True, help_text='The git command used for this run', null=True),
        ),
        migrations.AddField(
            model_name='playbookrun',
            name='git_stderr',
            field=models.TextField(blank=True, help_text='Stderr from git clone', null=True),
        ),
        migrations.AddField(
            model_name='playbookrun',
            name='git_stdout',
            field=models.TextField(blank=True, help_text='Stdout from git clone', null=True),
        ),
    ]
